webcoso/Models/NhomSanPham.cs
namespace webcoso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NhomSanPham")]
    public partial class NhomSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhomSanPham()
        {
            SanPhams = new HashSet<SanPham>();
        }

        [Key]
        public int MaNhom { get; set; }

        [StringLength(30)]
        public string TenNhom { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

webcoso/Controllers/NhomSanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webcoso.Models;
using PagedList;
using webcoso.Message;

namespace webcoso.Controllers
{
    public class NhomSanPhamsController : Controller
    {
        private WebcosoContext db = new WebcosoContext();
        private ApplicationDbContext data = new ApplicationDbContext();

        // GET: NhomSanPham
        public ActionResult Index(int? page)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (page == null) page = 1;
            var all_sach = (from s in db.NhomSanPham select s).OrderBy(m => m.MaNhom);
            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_sach.ToPagedList(pageNum, pageSize));
        }

        // GET: NhomSanPham/Details/5
        public ActionResult Details(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webcoso.Models.NhomSanPham nhomSanPham = db.NhomSanPham.Find(id);
            if (nhomSanPham == null)
            {
                return HttpNotFound();
            }
            return View(nhomSanPham);
        }

        // GET: NhomSanPham/Create
        public ActionResult Create()
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            return View();
        }

        // POST: NhomSanPham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNhom,TenNhom")] NhomSanPham nhomSanPham)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.NhomSanPham.Add(nhomSanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhomSanPham);
        }

        // GET: NhomSanPham/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhomSanPham nhomSanPham = db.NhomSanPham.Find(id);
            if (nhomSanPham == null)
            {
                return HttpNotFound();
            }
            return View(nhomSanPham);
        }

        // POST: NhomSanPham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNhom,TenNhom")] NhomSanPham nhomSanPham)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.Entry(nhomSanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhomSanPham);
        }

        // GET: NhomSanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhomSanPham nhomSanPham = db.NhomSanPham.Find(id);
            if (nhomSanPham == null)
            {
                return HttpNotFound();
            }
            return View(nhomSanPham);
        }

        // POST: NhomSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            NhomSanPham nhomSanPham = db.NhomSanPham.Find(id);
            if (db.SanPham.Where(p => p.MaNhom == nhomSanPham.MaNhom).FirstOrDefault() != null)
            {
                Notification.set_flash("Không thể xoá nhóm \' " + nhomSanPham.TenNhom + " \'!", "error");
                return RedirectToAction("Index");
            }
            Notification.set_flash("Đã xoá nhóm \' " + nhomSanPham.TenNhom + " \'!", "error");
            db.NhomSanPham.Remove(nhomSanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public bool AuthAdmin()
        {
            var user = data.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            if (user == null)
                return false;
            var userExist = user.Roles.FirstOrDefault(r => r.UserId == user.Id);
            if (userExist == null)
                return false;
            if (userExist.RoleId != "1")
                return false;
            return true;
        }
    }
}

webcoso/Views/NhomSanPhams/Create.cshtml
@model webcoso.Models.NhomSanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red; text-transform: capitalize;">Thêm nhóm sản phẩm</h2>
            @if (TempData["AlertMessage"] != null)
            {
                <div class="alert alert-success">
                    <strong>Success !</strong> @TempData["AlertMessage"]
                </div>}
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <strong class="control-label col-md-2">Tên nhóm</strong>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenNhom, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNhom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm" class="btn btn-success" />   |
                        <a class="btn btn-info" href='@Url.Action("Index", "NhomSanPhams")' style="margin:30px 0;">
                            Trở về
                        </a>
                    </div>
                </div>}
        </div>
    </main>
</div>

webcoso/Views/NhomSanPhams/Delete.cshtml
@model webcoso.Models.NhomSanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;">Xóa Nhóm Sản Phẩm</h2>

            <h3 class="text-center">Bạn có chắc chắn muốn xóa?</h3>
            <div>
                <hr />
                <div></div>
                <dl class="dl-horizontal" style="display:flex;justify-content:center;align-items:center;flex-direction:column">
                    <dt>
                        <strong>Tên Nhóm</strong>
                    </dt>
                    <dd style="font-size:20px">
                        @Html.DisplayFor(model => model.TenNhom)
                    </dd>


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <p>
                                <input type="submit" value="Xóa" class="btn btn-danger" /> |
                                <a class="btn btn-info" href='@Url.Action("Index", "NhomSanPhams")' style="margin:10px 0px;">
                                    Trở về
                                </a>
                            </p>
                        </div>
                    }
                </dl>
            </div>
        </div>
    </main>
</div>

webcoso/Views/NhomSanPhams/Details.cshtml
@model webcoso.Models.NhomSanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2>Thông tin chi tiết</h2>

            <div>
                <h4>Sản phẩm</h4>
                <hr />
                <dl class="dl-horizontal" style="margin-left:20px">
                    <dt>
                        @Html.DisplayNameFor(model => model.TenNhom)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenNhom)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Sửa", "Edit", new { id = Model.MaNhom }, new { @class = "btn btn-info" }) |
                <a class="btn btn-success" href='@Url.Action("Index", "NhomSanPhams")' style="margin:10px 0px;">
                    Trở về
                </a>
            </p>
        </div>
    </main>
</div>

webcoso/Views/NhomSanPhams/Edit.cshtml
@model webcoso.Models.NhomSanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">


            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;text-transform:capitalize">Chỉnh sửa nhóm sản phẩm</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="width:55%;margin:0 auto">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaNhom)

                    <div style="display:flex;justify-content:center;align-items:center;flex-direction:column;">
                        <div style="width:100%">
                            <strong class="control-label col-md-10">Tên nhóm</strong>
                            <div style="width:100%;padding:10px">
                                @Html.EditorFor(model => model.TenNhom, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenNhom, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-10 text-center">
                                <input type="submit" value="Lưu" class="btn btn-success" /> |
                                <a class="btn btn-info" href='@Url.Action("Index", "NhomSanPhams")' style="margin: 30px 0;">
                                    Trở về
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </main>
</div>

webcoso/Views/NhomSanPhams/Index.cshtml
@model PagedList.PagedList<webcoso.Models.NhomSanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <div>
                <div>
                    <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red; text-transform: capitalize;">Danh sách nhóm sản phẩm</h2>
                </div>
                <div style="display:flex;justify-content:right;margin:10px">
                    <form>
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Tìm kiếm theo nội dung..." aria-label="Tìm kiếm theo nội dung..." value="@ViewBag.Keyword" name="searchString" aria-describedby="btnNavbarSearch" />
                            <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>

            <a class="btn btn-success" href="@Url.Action("Create", "NhomSanPhams")" style="margin:10px 0px;">
                Thêm nhóm sản phẩm
            </a>
           
            <table class="table table-bordered table-dark">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Tên nhóm
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody class="table-light">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenNhom)
                            </td>
                            <td>
                                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.MaNhom }, new { @class = "btn btn-warning", @style = "margin-left:5px" }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.MaNhom }, new { @class = "btn btn-danger", @style = "margin-left:5px" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div style=" margin-bottom:50px;">
                <div>
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                </div>
                <div class="MenuTrang">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
                </div>
            </div>
        </div>
    </main>
</div>