webcoso/Controllers/ThuongHieuxController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webcoso.Models;
using webcoso.Models.LinQ;
using PagedList;
using webcoso.Message;

namespace websitelaptop.Controllers
{
    public class ThuongHieuxController : Controller
    {
        private WebcosoContext db = new WebcosoContext();
        private ApplicationDbContext data = new ApplicationDbContext();


        // GET: ThuongHieux
        public ActionResult Index(int? page)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (page == null) page = 1;
            var all_sach = (from s in db.ThuongHieu select s).OrderBy(m => m.MaTH);
            int pageSize = 5;
            int pageNum = page ?? 1;
            return View(all_sach.ToPagedList(pageNum, pageSize));
        }

        // GET: ThuongHieux/Details/5
        public ActionResult Details(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webcoso.Models.ThuongHieu thuongHieu = db.ThuongHieu.Find(id);
            if (thuongHieu == null)
            {
                return HttpNotFound();
            }
            return View(thuongHieu);
        }

        // GET: ThuongHieux/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThuongHieux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTH,TenTH")] webcoso.Models.ThuongHieu thuongHieu)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.ThuongHieu.Add(thuongHieu);
                db.SaveChanges();
                Notification.set_flash("Thêm thương hiệu \' " + thuongHieu.TenTH + " \' thành công!", "success");
                return RedirectToAction("Index");
            }

            return View(thuongHieu);
        }

        // GET: ThuongHieux/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webcoso.Models.ThuongHieu thuongHieu = db.ThuongHieu.Find(id);
            if (thuongHieu == null)
            {
                return HttpNotFound();
            }
            return View(thuongHieu);
        }

        // POST: ThuongHieux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTH,TenTH")] webcoso.Models.ThuongHieu thuongHieu)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                Notification.set_flash("Chỉnh sửa thành công!", "success");
                db.Entry(thuongHieu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thuongHieu);
        }

        // GET: ThuongHieux/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webcoso.Models.ThuongHieu thuongHieu = db.ThuongHieu.Find(id);
            if (thuongHieu == null)
            {
                return HttpNotFound();
            }
            return View(thuongHieu);
        }

        // POST: ThuongHieux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            webcoso.Models.ThuongHieu thuongHieu = db.ThuongHieu.Find(id);
            if (db.SanPham.Where(p => p.MaTH == thuongHieu.MaTH).FirstOrDefault() != null)
            {
                Notification.set_flash("Không thể xoá thương hiệu \' " + thuongHieu.TenTH + " \'!", "error");
                return RedirectToAction("Index");
            }
            db.ThuongHieu.Remove(thuongHieu);
            db.SaveChanges();
            Notification.set_flash("Đã xoá thương hiệu \' " + thuongHieu.TenTH + " \'!", "success");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public bool AuthAdmin()
        {
            var user = data.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            if (user == null)
                return false;
            var userExist = user.Roles.FirstOrDefault(r => r.UserId == user.Id);
            if (userExist == null)
                return false;
            if (userExist.RoleId != "1")
                return false;
            return true;
        }
    }
}

webcoso/Views/ThuongHieux/Create.cshtml
@model webcoso.Models.ThuongHieu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;">Thêm Thương Hiệu</h2>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <strong class="control-label col-md-2">
                           Tên Thương Hiệu
                        </strong>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenTH, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenTH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm" class="btn btn-success" />   |
                        <a class="btn btn-success" href='@Url.Action("Index", "ThuongHieux")' style="margin:30px 0;">
                            Trở về
                        </a>
                    </div>
                </div>}
        </div>
    </main>
</div>

webcoso/Views/ThuongHieux/Delete.cshtml
@model webcoso.Models.ThuongHieu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
                <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;">Xóa Thương Hiệu</h2>

                <h3 class="text-center">Bạn có chắc chắn muốn xóa?</h3>
                <div>
                    <hr />
                    <div></div>
                    <dl class="dl-horizontal" style="display:flex;justify-content:center;align-items:center;flex-direction:column">
                        <dt>
                            <strong>Tên Thương Hiệu</strong>
                        </dt>
                        <dd style="font-size:20px">
                            @Html.DisplayFor(model => model.TenTH)
                        </dd>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <p>
                                    <input type="submit" value="Xóa" class="btn btn-danger" /> |
                                    <a class="btn btn-info" href='@Url.Action("Index", "ThuongHieux")' style="margin:10px 0px;">
                                        Trở về
                                    </a>
                                </p>
                            </div>
                        }
                    </dl>

                </div>
        </div>
    </main>
</div>

webcoso/Views/ThuongHieux/Details.cshtml
@model webcoso.Models.ThuongHieu

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2>Thông tin chi tiết</h2>

            <div>
                <h4>Sản phẩm</h4>
                <hr />
                <dl class="dl-horizontal" style="margin-left:20px">
                    <dt>
                        @Html.DisplayNameFor(model => model.TenTH)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenTH)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Sửa", "Edit", new { id = Model.MaTH }, new { @class = "btn btn-info" }) |
                <a class="btn btn-success" href='@Url.Action("Index", "ThuongHieux")' style="margin:10px 0px;">
                    Trở về
                </a>
            </p>
        </div>
    </main>
</div>

webcoso/Views/ThuongHieux/Edit.cshtml
@model webcoso.Models.ThuongHieu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;">Chỉnh Sửa Thương Hiệu</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal" style="width:55%;margin:0 auto">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaTH)

                    <div style="display:flex;justify-content:center;align-items:center;flex-direction:column;">
                        <div style="width:100%">
                            <strong class="control-label col-md-10">Tên Thương hiệu</strong>
                            <div style = "width:100%;padding:10px">
                                @Html.EditorFor(model => model.TenTH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenTH, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-md-10 text-center">
                                <input type="submit" value="Lưu" class="btn btn-info" /> |
                                <a class="btn btn-success" href='@Url.Action("Index", "ThuongHieux")' style="margin: 30px 0;">
                                    Trở về
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </main>
</div>

webcoso/Views/ThuongHieux/Index.cshtml
@model PagedList.PagedList<webcoso.Models.ThuongHieu>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@Html.Partial("_MessageAlert")
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <div>
                <div>
                    <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red; text-transform: capitalize;">Danh sách thương hiệu</h2>
                </div>
                <div style="display:flex;justify-content:right;margin:10px">
                    <form>
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Tìm kiếm theo nội dung..." aria-label="Tìm kiếm theo nội dung..." value="@ViewBag.Keyword" name="searchString" aria-describedby="btnNavbarSearch" />
                            <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
            @Html.ActionLink("Thêm thương hiệu", "Create", "", new { @class = "btn btn-success", @style = "margin:10px" })
            <table class="table table-bordered table-dark">

                <thead class="thead-dark">
                    <tr>
                        <th>
                            Tên Thương Hiệu
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody class="table-light">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenTH)
                            </td>
                            <td>
                                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.MaTH }, new { @class = "btn btn-warning", @style = "margin-left:5px" }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.MaTH }, new { @class = "btn btn-danger", @style = "margin-left:5px" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div style=" margin-bottom:50px;">
                <div>
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                </div>
                <div class="MenuTrang">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
                </div>
            </div>
        </div>
    </main>
</div>