webcoso/Models/LoaiSP.cs
namespace webcoso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("LoaiSP")]
    public partial class LoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            SanPham = new HashSet<SanPham>();
        }

        [Key]
        public int MaLoai { get; set; }

        [StringLength(30)]
        public string TenLoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }

        public static List<LoaiSP> getAll(string searchKey)
        {
            WebcosoContext db = new WebcosoContext();
            searchKey = searchKey + "";
            return db.LoaiSP.Where(p => p.TenLoai.Contains(searchKey)).ToList();
        }
    }
}

webcoso/Controllers/LoaiSPsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webcoso.Models;
using PagedList;
using webcoso.Message;

namespace webcoso.Controllers
{
    public class LoaiSPsController : Controller
    {
        // GET: LoaiSPs
        private WebcosoContext db = new WebcosoContext();
        private ApplicationDbContext data = new ApplicationDbContext();

        // GET: LoaiSPs
        public ActionResult Index(int? page, string searchString)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            ViewBag.Keyword = searchString;
            //var all_loaiSP = db.LoaiSP.ToList();
            int pageSize = 10;
            int pageNum = page ?? 1;
            return View(LoaiSP.getAll(searchString).ToPagedList(pageNum, pageSize));
        }

        // GET: LoaiSPs/Details/5
        public ActionResult Details(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // GET: LoaiSPs/Create
        public ActionResult Create()
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            return View();
        }

        // POST: LoaiSPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLoai,TenLoai")] LoaiSP loaiSP)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.LoaiSP.Add(loaiSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiSP);
        }

        // GET: LoaiSPs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: LoaiSPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLoai,TenLoai")] LoaiSP loaiSP)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (ModelState.IsValid)
            {
                db.Entry(loaiSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiSP);
        }

        // GET: LoaiSPs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (loaiSP == null)
            {
                return HttpNotFound();
            }
            return View(loaiSP);
        }

        // POST: LoaiSPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!AuthAdmin())
                return RedirectToAction("Error401", "Admin");
            LoaiSP loaiSP = db.LoaiSP.Find(id);
            if (db.SanPham.Where(p => p.MaLoai == loaiSP.MaLoai).FirstOrDefault() != null)
            {
                Notification.set_flash("Không thể xoá loại \' " + loaiSP.TenLoai + " \'!", "error");
                return RedirectToAction("Index");
            }
            Notification.set_flash("Đã xoá loại \' " + loaiSP.TenLoai + " \'!", "error");
            db.LoaiSP.Remove(loaiSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public bool AuthAdmin()
        {
            var user = data.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            if (user == null)
                return false;
            var userExist = user.Roles.FirstOrDefault(r => r.UserId == user.Id);
            if (userExist == null)
                return false;
            if (userExist.RoleId != "1")
                return false;
            return true;
        }
    }
}

webcoso/Views/LoaiSPs/Create.cshtml
@model webcoso.Models.LoaiSP

@{ ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red; text-transform: capitalize;">Thêm loại sản phẩm </h2>

            @using (Html.BeginForm())
            {
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <strong class="control-label col-md-2">Tên loại</strong>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm" class="btn btn-success" />   |
                            <a class="btn btn-info" href='@Url.Action("Index", "LoaiSPs")' style="margin:10px 0px;">
                                Trở về
                            </a>
                        </div>
                    </div>
                </div>}
        </div>
    </main>
</div>

webcoso/Views/LoaiSPs/Delete.cshtml
@model webcoso.Models.LoaiSP

@{ ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">

            <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red;">Xóa Loại Sản Phẩm</h2>

            <h3 class="text-center">Bạn có chắc chắn muốn xóa?</h3>
            <div>
                <hr />
                <div></div>
                <dl class="dl-horizontal" style="display:flex;justify-content:center;align-items:center;flex-direction:column">
                    <dt>
                        <strong>Tên Loại</strong>
                    </dt>
                    <dd style="font-size:20px">
                        @Html.DisplayFor(model => model.TenLoai)
                    </dd>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-danger" /> |
                            <a class="btn btn-info" href='@Url.Action("Index", "LoaiSPs")' style="margin:10px 0px;">
                                Trở lại
                            </a>
                        </div>
                    }
                </dl>

            </div>
        </div>
    </main>
</div>

webcoso/Views/LoaiSPs/Details.cshtml
@model webcoso.Models.LoaiSP
@{ ViewBag.Title = "Details";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4" style=" margin-top:20px;">

            <h2>Thông tin chi tiết</h2>

            <div>
                <h4>Loại sản phẩm</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        Tên loại
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenLoai)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Sửa", "Edit", new { id = Model.MaLoai }, new { @class = "btn btn-warning" }) |
                <a class="btn btn-info" href='@Url.Action("Index", "LoaiSPs")' style="margin:10px 0px;">
                    Trở về
                </a>
            </p>
        </div>
    </main>
</div>

webcoso/Views/LoaiSPs/Edit.cshtml
@model webcoso.Models.LoaiSP
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h2 style=" margin-top:20px;">Chỉnh sửa loại sản phẩm</h2>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaLoai)

                    <div class="form-group">
                        <strong class="control-label col-md-2">Tên loại</strong>
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.TenLoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu" class="btn btn-success" /> |
                        <a class="btn btn-info" href='@Url.Action("Index", "LoaiSPs")' style="margin:10px 0px;">
                            Trở về
                        </a>
                    </div>


                </div>}
        </div>
    </main>
</div>

webcoso/Views/LoaiSPs/Index.cshtml
@model PagedList.PagedList<webcoso.Models.LoaiSP>
@using PagedList.Mvc;
@{ ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }


<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <div>
                <div>
                    <h2 style="text-align: center; margin-top: 20px; font-weight: bold; color: red; text-transform: capitalize;">Danh sách loại sản phẩm</h2>
                </div>
                <div style="display:flex;justify-content:right;margin:10px">
                    <form>
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Tìm kiếm theo tên..." aria-label="Tìm kiếm theo tên..." value="@ViewBag.Keyword" name="searchString" aria-describedby="btnNavbarSearch" />
                            <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </form>
                </div>
                
            </div>
            <a class="btn btn-success" href="@Url.Action("Create", "LoaiSPs")" style="margin:10px 0px;">
              Thêm loại sản phẩm
            </a>
            <table class="table table-bordered table-dark">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Tên loại sản phẩm
                        </th>
                        <th class="text-center">Thao tác</th>
                    </tr>
                </thead>
                <tbody class="table-light">
                    @foreach (var item in Model)
                    {
        <tr>
            <td class="col-lg-9">
                @Html.DisplayFor(modelItem => item.TenLoai)
            </td>
            <td class="col-lg-3 text-center">
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.MaLoai }, new { @class = "btn btn-warning" }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaLoai }, new { @class = "btn btn-danger", @style = "margin-left:5px" })
            </td>
        </tr>
}
                </tbody>
            </table>
            <div style=" margin-bottom:50px;">
                <div>
                    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                </div>
                <div class="MenuTrang">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
                </div>
            </div>
        </div>
    </main>
</div>